# Generated by Django 4.2.5 on 2023-09-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movie_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='thumbnail',
            new_name='poster',
        ),
    ]
